name: Garden Application CI

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet restore "Garden Application.sln"

      - run: dotnet build "Garden Application.sln" --configuration Release --no-restore

      - run: dotnet test "Garden Application.sln" --configuration Release --no-build
        continue-on-error: true

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - run: docker build -t ${{ secrets.DOCKER_USERNAME }}/garden-application:latest .

      - run: docker push ${{ secrets.DOCKER_USERNAME }}/garden-application:latest
